
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8080:8080/tcp" #set to 8080, bc nextcloud is running on port 80
      # Default HTTPs Port. FTL will generate a self-signed certificate
      - "8443:8443/tcp" #set to 8443, bc nextcloud is running on port 443
    environment:
      TZ: 'Europe/Copenhagen'
      FTLCONF_webserver_api_password: '4Glemsommekatte.' # is used for singing in to the web app.
      FTLCONF_dns_listeningMode: 'all'
    volumes:
      - './etc-pihole:/etc/pihole' #reccomended/common place to store pihole stuff.
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      # See https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
      - NET_ADMIN
      - SYS_TIME
      - SYS_NICE
    networks:
      - proxy-tier
    restart: unless-stopped

networks:
  proxy-tier:
    external: true



